spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_sercurity
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: trailheadsalesforce7@gmail.com
    password: hcex rnsq usqm esba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 6250655368566B5970337336763979244226452948404D635166546A576E5A71
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days